services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/run/sockets
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network

  api1:
    container_name: rinha-api1
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-pkg-cache:/go/pkg/mod
      - sockets:/run/sockets
    environment:
      - SOCKET_PATH=/run/sockets/api1.sock
      - AIR_CONFIG=${AIR_CONFIG:-air.toml}
    ports:
      - "2345:2345"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - rinha-network

  api2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-pkg-cache:/go/pkg/mod
      - sockets:/run/sockets
    environment:
      - SOCKET_PATH=/run/sockets/api2.sock
    networks:
      - rinha-network

volumes:
  go-build-cache:
  go-pkg-cache:
  sockets:

networks:
  rinha-network:
    driver: bridge
