worker_processes 1;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/stderr warn;

    upstream api {
        server unix:/run/sockets/api1.sock;
        server unix:/run/sockets/api2.sock;
        keepalive 100;
        keepalive_requests 10000;
    }

    server {
        listen 9999;

        keepalive_timeout 65s;

        location / {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_connect_timeout  5s;
            proxy_send_timeout    30s;
            proxy_read_timeout    30s;
        }
    }
}
